#!/bin/sh
set -eu

case "$1" in
purge)
	# Nothing to do
	;;
remove | upgrade | failed-upgrade | abort-install | abort-upgrade | disappear)
	# Nothing to do
	;;
*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
