#!/usr/bin/env sh
set -eu

case "$1" in
configure)
	# Nothing to do
	;;

abort-upgrade | abort-remove | abort-deconfigure)
	# Nothing to do
	;;
*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
