name: Check
on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  check-ca-certificates:
    name: "Check ca-certificates"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          export _JAVA_OPTIONS="-Xmx4G"
          ./gradlew --parallel :ca-certificates:check --stacktrace

  check:
    name: "Check ${{ matrix.product.name }} ${{ matrix.product.version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # No Docker on macOS
        # https://github.community/t/is-it-possible-to-install-and-configure-docker-on-macos-runner/16981/8
        product: [
          { name: dragonwell, version: 11 },
          { name: temurin, version: 11 },
          { name: temurin, version: 16 },
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          export _JAVA_OPTIONS="-Xmx4G"
          ./gradlew --parallel check -PPRODUCT=${{ matrix.product.name }} -PPRODUCT_VERSION=${{ matrix.product.version }} --stacktrace
